version: '3'

services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: aftas3
    ports:
      - "5432:5432"

  spring-application-back:
    build:
      context: ./aftas
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/aftas3?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root

  spring-application-front:
    build:
      context: ./aftas-frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - spring-application-back